name: getGPDFdR
on:
  schedule:
    - cron: '0 7 * * *'
    
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd ./python/gpd-report
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          PG_USER_NAME: "apduser"
          FR_NEW_CONN_SUBKEY_UAT: ${{ secrets.PG_APD_PASSWORD }}

        run: |
          cd ./python/gpd-report
          python debt-position-report.py

      - name: Create failure payload
        if: ${{ failure() && inputs.notify }}
        run: |
          echo '{
            "text": "❌ *GPD Report Generation Failed.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Si è verificato un errore durante la generazione del report GPD*"
                }
              }
            ]
          }' > ./python/gpd-report/report.json
          
      - name: Send notification to Slack
        id: slack
        if: ${{ (success() || failure()) && (inputs.notify != 'false' || github.event_name == 'schedule') }}
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
        with: 
            payload-file-path: "./python/gpd-report/report.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK          
      
