name: GPD SMO Report
on:
  schedule:
    - cron: '0 7 * * 1'
    
  workflow_dispatch:
    inputs:  
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - uat
          - prod
        default: prod
      notify:
        description: 'notify report results'
        required: false
        type: boolean
        default: true
          
permissions:
  id-token: write
  contents: read
  deployments: write

jobs:

  approve_create_runner:
    name: Execute auto-approve for 'Create Runner'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs == null || github.event.inputs == 'prod' }}
    steps:    
      - name: Auto approve
        uses: andrea-deri/auto-approve@042a1e58fa51acef74997dc9cebb1c665677d2ac
        with:
          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          environment: ${{ inputs.environment || 'prod' }}
        
  create_runner:
    name: Create Runner
    runs-on: ubuntu-22.04
    environment:
      name: ${{(github.event.inputs == null && 'prod') || inputs.environment }}
    outputs:
      runner_name: ${{ steps.create_github_runner.outputs.runner_name }}
    steps:     
      - name: Create GitHub Runner
        id: create_github_runner
        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-create-action@main
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          container_app_environment_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_NAME }}
          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }} # RG of the runner
          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          self_hosted_runner_image_tag: "latest"
      - name: Install dependencies
        run: |
          export RUNNER_ALLOW_RUNASROOT="1"
          sudo apt-get update && sudo apt-get install -y libpq-dev

  approve_report_script:
    needs: [ create_runner ]
    name: Execute auto-approve for 'Report Script'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs == null || github.event.inputs == 'prod' }}
    steps:
      - name: Auto approve
        uses: andrea-deri/auto-approve@042a1e58fa51acef74997dc9cebb1c665677d2ac
        with:
          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          environment: ${{ inputs.environment || 'prod' }} 

  
  report_script:
    needs: [ create_runner ]
    name: Report GPD APD prod
    runs-on: [ self-hosted, "${{ needs.create_runner.outputs.runner_name }}" ]
    environment: prod

    steps:
        
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.12'
        
      - name: Check out the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
            
      - name: Install dependencies
        run: |
          cd ./python/gpd-report
          pip install -r requirements.txt

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run Report
        shell: bash
        env:
          PG_USER_NAME: "apduser"
          PG_DB_NAME: "apd"
          PG_APD_PASSWORD: ${{ github.event_name == 'schedule' && secrets.PG_APD_PASSWORD || (inputs.environment == 'prod' && secrets.PG_APD_PASSWORD || secrets.PG_APD_UAT_PASSWORD) }}
          PG_HOST: ${{ github.event_name == 'schedule' && 'pagopa-p-weu-gpd-pgflex.postgres.database.azure.com' || (inputs.environment == 'prod' && 'pagopa-p-weu-gpd-pgflex.postgres.database.azure.com' || 'pagopa-u-weu-gpd-pgflex.postgres.database.azure.com') }}
          PG_PORT: "6432"
          PYTHONUNBUFFERED: "1"

        run: |
          cd ./python/gpd-report
          python debt-position-report.py

      - name: Create failure payload
        if: ${{ failure() && inputs.notify }}
        run: |
          echo '{
            "text": "❌ *GPD Report Generation Failed.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Si è verificato un errore durante la generazione del report GPD*"
                }
              }
            ]
          }' > ./python/gpd-report/report.json
          
      - name: Send notification to Slack
        id: slack
        if: ${{ (success() || failure()) && (inputs.notify != 'false' || github.event_name == 'schedule') }}
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
        with: 
            payload-file-path: "./python/gpd-report/report.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GPD_APD_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  approve_cleanup_runner:
    needs: [ report_script ]
    name: Execute auto-approve for 'Cleanup Runner'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs == null || github.event.inputs == 'prod' }}
    steps:        
      - name: Auto approve
        uses: andrea-deri/auto-approve@042a1e58fa51acef74997dc9cebb1c665677d2ac
        with:
          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          environment: ${{ inputs.environment || 'prod' }}

  cleanup_runner:
    name: Cleanup Runner
    needs: [ create_runner, report_script ]
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    environment: ${{(github.event.inputs == null && 'uat') || inputs.environment }}
    steps:
      - name: Cleanup GitHub Runner
        id: cleanup_github_runner
        # from https://github.com/pagopa/eng-github-actions-iac-template/tree/main/azure/github-self-hosted-runner-azure-cleanup-action
        uses: pagopa/eng-github-actions-iac-template/azure/github-self-hosted-runner-azure-cleanup-action@0ee2f58fd46d10ac7f00bce4304b98db3dbdbe9a
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          resource_group_name: ${{ vars.CONTAINER_APP_ENVIRONMENT_RESOURCE_GROUP_NAME }}
          runner_name: ${{ needs.create_runner.outputs.runner_name }}
          pat_token: ${{ secrets.BOT_TOKEN_GITHUB }}
      
