name: Scheduled Maintenance to Betterstack Daily Script Execution

# Imposta il workflow per essere eseguito ogni giorno alle 00:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Imposta Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Installa le dipendenze (se presenti)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Esegui lo script Python
    - name: Run the Python script
      env:
        BETTERSTACK_TOKEN: ${{ secrets.BETTER_STACK_TOKEN }}
        PAGOPA_SUBSCRIPTION_KEY: ${{ secrets.PAGOPA_BACKOFFICE_API_KEY_UAT }}
      run: |
        python station_maintenance.py
